[package]
name = "clpx_bootstrapping"
version = "0.1.0"
edition = "2024"

[dependencies]
feanor-math = "3.5.0"
fheanor = { git = "https://github.com/feanortheelf/fheanor" }
rand = "0.9.2"
tracing = "0.1.41"
